In [2]:
import tensorflow as tf

In [4]:
a = tf.constant([[1., 2, 3],
                 [4, 5, 6],])
print(a)
print(a.shape)
print(a.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [13]:
print(a + a)
print(5 * a)
print(tf.transpose(a))
print(tf.concat([a, a], axis=0))

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 5. 10. 15.]
 [20. 25. 30.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]], shape=(4, 3), dtype=float32)


In [25]:
print(tf.nn.softmax(a, axis=0))     # softmax along the columns
print(tf.reduce_sum(a))             # sum all elements

tf.Tensor(
[[0.04742587 0.04742587 0.04742587]
 [0.95257413 0.95257413 0.95257413]], shape=(2, 3), dtype=float32)
tf.Tensor(21.0, shape=(), dtype=float32)


In [27]:
import numpy as np
b = np.array([1., 2, 3])
print(b.dtype)
print(tf.convert_to_tensor(b))

float64
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [30]:
tf.config.list_physical_devices()       # List of all the physical devices used by tensorflow

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [31]:
# Condition to print if GPU is being used
if tf.config.list_physical_devices('GPU'):
    print("Tensorflow is using the GPU")
else:
    print("Tensorflow is not using the GPU")

Tensorflow is using the GPU


In [35]:
var = tf.Variable([0.0, 0.0, 0.0])
var.assign([1, 2, 3])
var.assign_add([1, 2, 3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 4., 6.], dtype=float32)>

In [36]:
x = tf.Variable(1.0)

def f(x):
    y = x**2 + 2*x - 5
    return y
f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [42]:
with tf.GradientTape() as tape:
    y = f(x)
g_x = tape.gradient(y, x)
g_x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>